on: push
name: Build & Release
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        ./build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
